/**
 * Comprehensive Catalog Data Structure
 * Hardcoded data matching the Catalog requirements
 */

// Categories
export const CATEGORIES_DATA = [
  { id: "cat-1", name: "Court Rental", visibility: "active", displayOrder: 1 },
  { id: "cat-2", name: "Equipment", visibility: "active", displayOrder: 2 },
  { id: "cat-3", name: "Beverages", visibility: "active", displayOrder: 3 },
  { id: "cat-4", name: "Lessons", visibility: "active", displayOrder: 4 },
];

// Products with full catalog structure
export const CATALOG_PRODUCTS = [
  {
    id: 1,
    name: "Court Rental - 1 Hour",
    description: "Standard court rental for 1 hour of play time",
    sku: "CR-001",
    basePrice: 25.0,
    categoryId: "cat-1",
    hasVariants: false,
    imageUrls: [],
    tags: ["rental", "court"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    // Inventory
    inventory: {
      currentStock: 10,
      reservedStock: 0,
      reorderPoint: 5,
      lowStockThreshold: 3,
      isEnabled: true,
      stockState: "in_stock",
    },
    // Promotion
    promotion: {
      isPromoted: false,
      priority: 0,
      promoLabel: null,
      startDate: null,
      endDate: null,
      isActive: false,
    },
  },
  {
    id: 2,
    name: "Court Rental - 2 Hours",
    description: "Extended court rental for 2 hours of play time",
    sku: "CR-002",
    basePrice: 45.0,
    categoryId: "cat-1",
    hasVariants: true,
    variantType: "Court Type",
    imageUrls: [],
    tags: ["rental", "court"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    variants: [
      {
        id: "standard",
        name: "Standard Court",
        sku: "CR-002-STD",
        price: 45.0,
        imageUrl: null,
        inventory: {
          currentStock: 5,
          reservedStock: 0,
          reorderPoint: 3,
          lowStockThreshold: 2,
          isEnabled: true,
          stockState: "in_stock",
        },
      },
      {
        id: "premium",
        name: "Premium Court",
        sku: "CR-002-PRM",
        price: 60.0,
        imageUrl: null,
        inventory: {
          currentStock: 2,
          reservedStock: 0,
          reorderPoint: 3,
          lowStockThreshold: 2,
          isEnabled: true,
          stockState: "low_stock",
        },
      },
      {
        id: "championship",
        name: "Championship Court",
        sku: "CR-002-CHM",
        price: 75.0,
        imageUrl: null,
        inventory: {
          currentStock: 0,
          reservedStock: 0,
          reorderPoint: 2,
          lowStockThreshold: 1,
          isEnabled: true,
          stockState: "out_of_stock",
        },
      },
    ],
    // Base inventory (for products with variants, this is usually 0)
    inventory: {
      currentStock: 0,
      reservedStock: 0,
      reorderPoint: 0,
      lowStockThreshold: 0,
      isEnabled: true,
      stockState: "in_stock",
    },
    // Promotion
    promotion: {
      isPromoted: true,
      priority: 2,
      promoLabel: "Popular",
      startDate: "2024-01-01T00:00:00Z",
      endDate: null,
      isActive: true,
    },
  },
  {
    id: 3,
    name: "Racket Rental",
    description: "Standard racket rental for court play",
    sku: "EQ-001",
    basePrice: 5.0,
    categoryId: "cat-2",
    hasVariants: false,
    imageUrls: [],
    tags: ["rental", "equipment"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-18T09:15:00Z",
    inventory: {
      currentStock: 0,
      reservedStock: 0,
      reorderPoint: 5,
      lowStockThreshold: 3,
      isEnabled: true,
      stockState: "out_of_stock",
    },
    promotion: {
      isPromoted: false,
      priority: 0,
      promoLabel: null,
      startDate: null,
      endDate: null,
      isActive: false,
    },
  },
  {
    id: 4,
    name: "Racket Rental - Premium",
    description: "Premium racket rental with advanced features",
    sku: "EQ-002",
    basePrice: 8.0,
    categoryId: "cat-2",
    hasVariants: true,
    variantType: "Racket Type",
    imageUrls: [],
    tags: ["rental", "equipment", "premium"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-18T09:15:00Z",
    variants: [
      {
        id: "beginner",
        name: "Beginner",
        sku: "EQ-002-BEG",
        price: 8.0,
        inventory: {
          currentStock: 10,
          reservedStock: 0,
          reorderPoint: 5,
          lowStockThreshold: 3,
          isEnabled: true,
          stockState: "in_stock",
        },
      },
      {
        id: "intermediate",
        name: "Intermediate",
        sku: "EQ-002-INT",
        price: 12.0,
        inventory: {
          currentStock: 3,
          reservedStock: 0,
          reorderPoint: 5,
          lowStockThreshold: 3,
          isEnabled: true,
          stockState: "low_stock",
        },
      },
      {
        id: "professional",
        name: "Professional",
        sku: "EQ-002-PRO",
        price: 15.0,
        inventory: {
          currentStock: 0,
          reservedStock: 0,
          reorderPoint: 3,
          lowStockThreshold: 2,
          isEnabled: true,
          stockState: "out_of_stock",
        },
      },
    ],
    inventory: {
      currentStock: 0,
      reservedStock: 0,
      reorderPoint: 0,
      lowStockThreshold: 0,
      isEnabled: true,
      stockState: "in_stock",
    },
    promotion: {
      isPromoted: true,
      priority: 1,
      promoLabel: "New",
      startDate: "2024-01-15T00:00:00Z",
      endDate: null,
      isActive: true,
    },
  },
  {
    id: 5,
    name: "Balls (3 pack)",
    description: "Set of 3 professional squash balls",
    sku: "EQ-003",
    basePrice: 8.0,
    categoryId: "cat-2",
    hasVariants: false,
    imageUrls: [],
    tags: ["equipment", "balls"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: true,
    metadata: {},
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-19T11:20:00Z",
    inventory: {
      currentStock: 15,
      reservedStock: 0,
      reorderPoint: 10,
      lowStockThreshold: 5,
      isEnabled: true,
      stockState: "in_stock",
    },
    promotion: {
      isPromoted: false,
      priority: 0,
      promoLabel: null,
      startDate: null,
      endDate: null,
      isActive: false,
    },
  },
  {
    id: 6,
    name: "Water Bottle",
    description: "Reusable water bottle for hydration",
    sku: "BEV-001",
    basePrice: 3.0,
    categoryId: "cat-3",
    hasVariants: true,
    variantType: "Size",
    imageUrls: [],
    tags: ["beverages", "hydration"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-14T10:00:00Z",
    updatedAt: "2024-01-17T16:45:00Z",
    variants: [
      {
        id: "small",
        name: "Small (500ml)",
        sku: "BEV-001-SML",
        price: 3.0,
        inventory: {
          currentStock: 0,
          reservedStock: 0,
          reorderPoint: 10,
          lowStockThreshold: 5,
          isEnabled: true,
          stockState: "out_of_stock",
        },
      },
      {
        id: "large",
        name: "Large (1L)",
        sku: "BEV-001-LRG",
        price: 5.0,
        inventory: {
          currentStock: 8,
          reservedStock: 0,
          reorderPoint: 10,
          lowStockThreshold: 5,
          isEnabled: true,
          stockState: "in_stock",
        },
      },
    ],
    inventory: {
      currentStock: 0,
      reservedStock: 0,
      reorderPoint: 0,
      lowStockThreshold: 0,
      isEnabled: true,
      stockState: "in_stock",
    },
    promotion: {
      isPromoted: false,
      priority: 0,
      promoLabel: null,
      startDate: null,
      endDate: null,
      isActive: false,
    },
  },
  {
    id: 7,
    name: "Energy Drink",
    description: "High-energy sports drink",
    sku: "BEV-002",
    basePrice: 4.0,
    categoryId: "cat-3",
    hasVariants: false,
    imageUrls: [],
    tags: ["beverages", "energy"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-13T10:00:00Z",
    updatedAt: "2024-01-16T13:30:00Z",
    inventory: {
      currentStock: 5,
      reservedStock: 0,
      reorderPoint: 10,
      lowStockThreshold: 5,
      isEnabled: true,
      stockState: "in_stock",
    },
    promotion: {
      isPromoted: false,
      priority: 0,
      promoLabel: null,
      startDate: null,
      endDate: null,
      isActive: false,
    },
  },
  {
    id: 8,
    name: "Towel Rental",
    description: "Clean towel rental for court use",
    sku: "EQ-004",
    basePrice: 2.0,
    categoryId: "cat-2",
    hasVariants: false,
    imageUrls: [],
    tags: ["rental", "equipment"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-11T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    inventory: {
      currentStock: 1,
      reservedStock: 0,
      reorderPoint: 5,
      lowStockThreshold: 3,
      isEnabled: true,
      stockState: "low_stock",
    },
    promotion: {
      isPromoted: false,
      priority: 0,
      promoLabel: null,
      startDate: null,
      endDate: null,
      isActive: false,
    },
  },
  {
    id: 9,
    name: "Grip Tape",
    description: "Professional racket grip tape",
    sku: "EQ-005",
    basePrice: 6.0,
    categoryId: "cat-2",
    hasVariants: false,
    imageUrls: [],
    tags: ["equipment", "accessories"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: true,
    metadata: {},
    createdAt: "2024-01-09T10:00:00Z",
    updatedAt: "2024-01-14T08:20:00Z",
    inventory: {
      currentStock: 20,
      reservedStock: 0,
      reorderPoint: 15,
      lowStockThreshold: 10,
      isEnabled: true,
      stockState: "in_stock",
    },
    promotion: {
      isPromoted: true,
      priority: 3,
      promoLabel: "Staff Pick",
      startDate: "2024-01-01T00:00:00Z",
      endDate: null,
      isActive: true,
    },
  },
  {
    id: 10,
    name: "Squash Shoes Rental",
    description: "Professional squash court shoes rental",
    sku: "EQ-006",
    basePrice: 10.0,
    categoryId: "cat-2",
    hasVariants: true,
    variantType: "Size",
    imageUrls: [],
    tags: ["rental", "equipment", "shoes"],
    status: "active",
    visibility: "active",
    inventoryTracking: true,
    discountEligible: false,
    metadata: {},
    createdAt: "2024-01-08T10:00:00Z",
    updatedAt: "2024-01-13T12:00:00Z",
    variants: [
      {
        id: "size-7",
        name: "Size 7",
        sku: "EQ-006-7",
        price: 10.0,
        inventory: {
          currentStock: 2,
          reservedStock: 0,
          reorderPoint: 3,
          lowStockThreshold: 2,
          isEnabled: true,
          stockState: "low_stock",
        },
      },
      {
        id: "size-8",
        name: "Size 8",
        sku: "EQ-006-8",
        price: 10.0,
        inventory: {
          currentStock: 5,
          reservedStock: 0,
          reorderPoint: 3,
          lowStockThreshold: 2,
          isEnabled: true,
          stockState: "in_stock",
        },
      },
      {
        id: "size-9",
        name: "Size 9",
        sku: "EQ-006-9",
        price: 10.0,
        inventory: {
          currentStock: 0,
          reservedStock: 0,
          reorderPoint: 3,
          lowStockThreshold: 2,
          isEnabled: true,
          stockState: "out_of_stock",
        },
      },
      {
        id: "size-10",
        name: "Size 10",
        sku: "EQ-006-10",
        price: 10.0,
        inventory: {
          currentStock: 1,
          reservedStock: 0,
          reorderPoint: 3,
          lowStockThreshold: 2,
          isEnabled: true,
          stockState: "low_stock",
        },
      },
    ],
    inventory: {
      currentStock: 0,
      reservedStock: 0,
      reorderPoint: 0,
      lowStockThreshold: 0,
      isEnabled: true,
      stockState: "in_stock",
    },
    promotion: {
      isPromoted: false,
      priority: 0,
      promoLabel: null,
      startDate: null,
      endDate: null,
      isActive: false,
    },
  },
];

// Activity Log Entries
export const ACTIVITY_LOG = [
  {
    id: "act-1",
    entityType: "product",
    entityId: 1,
    action: "created",
    performedBy: "admin",
    timestamp: "2024-01-15T10:00:00Z",
    changes: { name: { old: null, new: "Court Rental - 1 Hour" } },
    metadata: {},
  },
  {
    id: "act-2",
    entityType: "inventory",
    entityId: 1,
    action: "stock_adjusted",
    performedBy: "admin",
    timestamp: "2024-01-16T14:30:00Z",
    changes: { currentStock: { old: 5, new: 10 } },
    metadata: { reason: "Restocking" },
  },
  {
    id: "act-3",
    entityType: "product",
    entityId: 2,
    action: "promoted",
    performedBy: "admin",
    timestamp: "2024-01-17T09:00:00Z",
    changes: { promotion: { old: { isPromoted: false }, new: { isPromoted: true, promoLabel: "Popular" } } },
    metadata: {},
  },
  {
    id: "act-4",
    entityType: "inventory",
    entityId: 3,
    action: "stock_adjusted",
    performedBy: "admin",
    timestamp: "2024-01-18T11:15:00Z",
    changes: { currentStock: { old: 2, new: 0 } },
    metadata: { reason: "Checkout transaction" },
  },
  {
    id: "act-5",
    entityType: "product",
    entityId: 9,
    action: "promoted",
    performedBy: "admin",
    timestamp: "2024-01-19T10:20:00Z",
    changes: { promotion: { old: { isPromoted: false }, new: { isPromoted: true, promoLabel: "Staff Pick", priority: 3 } } },
    metadata: {},
  },
];

// Helper function to get product by ID
export function getProductById(productId) {
  return CATALOG_PRODUCTS.find((p) => p.id === productId);
}

// Helper function to get category by ID
export function getCategoryById(categoryId) {
  return CATEGORIES_DATA.find((c) => c.id === categoryId);
}

// Helper function to get activity log for product
export function getActivityLogForProduct(productId) {
  return ACTIVITY_LOG.filter(
    (log) => log.entityId === productId || log.entityType === "inventory"
  );
}
